- name: Setup MacOS
  hosts: 127.0.0.1

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  vars:
    homebrew_installed_packages:
      - antidote
      - azure-cli
      - Azure/kubelogin/kubelogin
      - bash-completion
      - dopplerhq/doppler/doppler
      - dotnet
      - gettext
      - git
      - git-extras
      - git-lfs
      - github/gh/gh
      - gpg
      - helm
      - helmfile
      - httpie
      - iperf
      - k6
      - kubernetes-cli
      - languagetool
      - libevent
      - libpq # postgres tooling
      - mcrypt
      - mysql-client
      - nano
      - neovim
      - nmap
      - openssl
      - podman
      - podman-compose
      - poetry
      - pulumi
      - pyenv
      - pv
      - readline
      - ssh-copy-id
      - sqlite
      - volta
      - wget
      - wrk
      - zsh-history-substring-search

    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - microsoft/git

    homebrew_cask_appdir: /Applications
    homebrew_cask_apps:
      - caffeine
      - clickup
      - cryptomator
      - cyberduck
      - discord
      - dozer # menu bar icon organization
      - figma
      - firefox
      - git-credential-manager-core
      - google-chrome
      - google-drive
      - handbrake
      - jetbrains-toolbox
      - lulu
      - microsoft-edge
      - microsoft-teams
      - mongodb-compass
      - notion
      - obsidian
      - podman-desktop
      - spotify
      - steam
      - raycast
      - rectangle
      - responsively
      - visual-studio-code
      - vlc
      - warp
      - zoom

    mas_installed_apps:
      - id: 1352778147
        name: Bitwarden
      - id: 1295203466
        name: Microsoft Remote Desktop
      - id: 462054704
        name: Microsoft Word
      - id: 462058435
        name: Microsoft Excel
      - id: 462062816
        name: Microsoft PowerPoint
      - id: 784801555
        name: Microsoft OneNote
      - id: 823766827
        name: OneDrive
      - id: 1085114709
        name: Parallels Desktop
      - id: 470158793
        name: Keka
      - id: 1490048917
        name: Taskade
      - id: 1346247457
        name: Endel

    configure_dock: true
    dockitems_remove:
      - Launchpad
      - Safari
      - Photos
      - FaceTime
      - Calendar
      - Contacts
      - Reminders
      - Notes
      - Freeform
      - Music
      - Keynote
      - Numbers
      - Pages
      - TV
      - Podcasts
      - App Store
      - System Settings
    dockitems_persist:
      - name: Microsoft Teams
        path: /Applications/Microsoft Teams.app/
      - name: Firefox
        path: /Applications/Firefox.app/
      - name: Warp
        path: /Applications/Warp.app/
      - name: Visual Studio Code
        path: /Applications/Visual Studio Code.app/
      - name: Endel
        path: /Applications/Endel.app/
      - name: Spotify
        path: /Applications/Spotify.app/
