- name: Setup ubuntu
  hosts: 127.0.0.1
  roles:
    - bootstrap
    - packages
    - git
    - docker
    - node
    # - java
    # - scala
    # - r
    - vpn
    - latex
  vars:
    account_name: roland

    # cpu_uv: 130
    # gpu_uv: 45

    git_user_name: Roland Schlaefli
    git_user_email: rolandschlaefli@gmail.com

    install_packages:
      - pomodone
      - caffeine
      - filezilla
      - vscode
      - neovim
      - cleaner
      - albert
      - git-standup
      - zsh
      - keybase
      - rescuetime

    install_snaps:
      # - gitkraken
      - spotify
      # - postman
      - redis-desktop-manager
      - chromium
      - writefull
      - bitwarden
      - bw
      - gravit-designer

    install_additional:
      - pdfshuffler
