- name: Setup ubuntu
  hosts: 127.0.0.1
  roles:
    - packages
    - zsh
    - git
    - docker
    - vscode
    - vpn
    # - latex
    - role: Comcast.sdkman
      sdkman_user: "{{account_name}}"
      sdkman_group: "{{account_name}}"
      sdkman_install_packages:
        - { candidate: java, version: 8.0.252.hs-adpt }
        - { candidate: java, version: 14.0.1.hs-adpt }
        - { candidate: sbt, version: 1.3.9 }
      sdkman_defaults:
        java: 8.0.242.hs-adpt
        sbt: 1.3.9
      sdkman_flush_caches_before:
        - temp
      sdkman_flush_caches_after:
        - archives
        - broadcast
        - candidates
        - temp
      sdkman_update_alternatives:
        - candidate: java
          name: java
          link: /usr/bin/java
        - candidate: java
          name: javac
          link: /usr/bin/javac
        - candidate: sbt
          name: sbt
          link: /usr/bin/sbt
    - role: ansible-role-nvm
      become: yes
      become_user: "{{account_name}}"
      nvm_commands:
        - "nvm install --lts"
        - "nvm install 12"
        - "nvm install 14"
        - "nvm alias default 12"
  vars:
    # GENERAL
    account_name: roland

    # PACKAGES
    packages_ppa:
      - ppa:agornostal/ulauncher

    packages_apt:
      - nano
      - htop
      - tilix
      - nemo
      - ufw
      - gufw
      - build-essential
      - git
      - caffeine
      - filezilla
      - pdfshuffler
      - git-extras

    packages_deb:
      # https://ulauncher.io/#Download
      - https://github.com/Ulauncher/Ulauncher/releases/download/5.7.0/ulauncher_5.7.0_all.deb
      # https://store.steampowered.com/linux
      - https://steamcdn-a.akamaihd.net/client/installer/steam.deb
      # https://pomodoneapp.com/download-pomodone-app.html#linux
      - https://app.pomodoneapp.com/installers/PomoDoneApp_1.5.1534_amd64.deb
      # https://www.rescuetime.com/download_linux
      - https://www.rescuetime.com/installers/rescuetime_current_amd64.deb
      # https://www.dropbox.com/install-linux
      - https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2020.03.04_amd64.deb
      # https://support.toggl.com/en/articles/2410832-toggl-desktop-for-linux
      - https://github.com/toggl-open-source/toggldesktop/releases/download/v7.4.528/toggldesktop_7.4.528_amd64.deb
      # https://products.office.com/de-ch/microsoft-teams/group-chat-software#desktopAppDownloadregion
      - https://go.microsoft.com/fwlink/p/?linkid=2112886
      # https://minetime.ai/
      - https://europe-west1-minetime-backend.cloudfunctions.net/download/linux-deb

    packages_snap_confined:
      - bitwarden
      - bw
      - chromium
      - gravit-designer
      - journey
      - postman
      - redis-desktop-manager
      - spotify

    packages_snap_classic:
      - heroku

    packages_startup:
      - { path: "/usr/bin/rescuetime", name: "RescueTime" }
      - { path: "/usr/bin/nemo-desktop", name: "nemo-desktop" }
      - { path: "/usr/bin/TogglDesktop.sh", name: "Toggl" }

    # GIT
    git_user_name: Roland Schlaefli
    git_user_email: rolandschlaefli@gmail.com
