- name: Setup ubuntu
  hosts: 127.0.0.1
  roles:
    - bootstrap
    - packages
    - git
    - docker
    - node
    - java
    - scala
    - r
    - vpn
    - latex
  vars:
    account_name: roland

    git_user_name: Roland Schlaefli
    git_user_email: rolandschlaefli@gmail.com

    install_packages:
      - pomodoro
      - caffeine
      - filezilla
      - copyq
      - vscode
      - nextcloud
      - neovim
      - cleaner
      - albert
      - git-standup
      - keybase
      - zsh

    install_snaps:
      - gitkraken
      - spotify
      - postman
      - redis-desktop-manager
      - chromium
      - writefull
      - bitwarden
      - bw
      - gravit-designer

    install_additional:
      - pdfshuffler

    cpu_uv: 130
    gpu_uv: 45
