---
# MacOS Setup Playbook
# This playbook configures a new macOS system with apps, settings, and development tools

- name: Setup MacOS
  hosts: 127.0.0.1
  connection: local
  become_method: sudo

  # Variables that can be customized
  vars:
    # User info for configuration
    user_full_name: "Roland Schlaefli"
    user_email: "rolandschlaefli@gmail.com"
    
    # Configuration toggles
    configure_dock: true
    configure_homebrew: true
    configure_mas: true
    configure_asdf: true
    configure_firewall: true
    configure_settings: true
    
    # Default paths
    homebrew_cask_appdir: "/Applications"

  roles:
    # Command Line Tools
    - role: elliotweiser.osx-command-line-tools
      tags: [core, xcode, tools]

    # Homebrew and applications
    - role: geerlingguy.mac.homebrew
      when: configure_homebrew | bool
      tags: [core, homebrew, apps]
      vars:
        homebrew_taps:
          - aviator-co/tap
        homebrew_installed_packages:
          - act
          - antidote
          - asdf
          - aviator-co/tap/av
          - azure-cli
          - kubelogin
          - bruno
          - btop
          - certbot
          - cocoapods
          - d2
          - k9s
          - devcontainer
          - docker
          - docker-credential-helper
          - dockutil
          - doppler
          - dotnet
          - draft
          - ffmpeg
          - fx
          - gettext
          - git
          - git-delta
          - git-extras
          - git-filter-repo
          - git-lfs
          - gh
          - gitleaks
          - gpg
          - graphviz
          - helm
          - helmfile
          - homeshick
          - httpie
          - infisical
          - iperf
          - k6
          - kompose
          - kubernetes-cli
          - languagetool
          - libevent
          - libpq # postgres tooling
          - mysql-client
          - nano
          - nmap
          - openssl
          - pandoc
          - pnpm
          - poetry
          - pulumi
          - pv
          - rancher
          - readline
          - redis
          - ripgrep
          - ruff
          - ssh-copy-id
          - sqlite
          - stern # k8s logging
          - uv
          - volta
          - wget
          - whisky
          - wrk
          - zrok

        homebrew_cask_apps:
          - bartender
          - caffeine
          - claude
          - clickup
          - crossover
          - cryptomator
          - cursor
          - cyberduck
          - discord
          - figma
          - git-credential-manager
          - google-chrome
          - handbrake
          - jetbrains-toolbox
          - lulu
          - mactex
          - malwarebytes
          - microsoft-edge
          - microsoft-teams
          - obsidian
          - redisinsight
          - spacedrive
          - spotify
          - steam
          - raycast
          - responsively
          - visual-studio-code
          - vlc
          - warp
          - windsurf
          - zen-browser
          - zoom

    # Mac App Store applications
    - role: geerlingguy.mac.mas
      when: configure_mas | bool and (mas_installed_apps or mas_installed_app_ids)
      tags: [apps, mas]
      vars:
        mas_installed_apps:
          - id: 6714467650
            name: Perplexity
          - id: 1487937127
            name: Craft
          - id: 1352778147
            name: Bitwarden
          - id: 1295203466
            name: Microsoft Remote Desktop
          - id: 462054704
            name: Microsoft Word
          - id: 462058435
            name: Microsoft Excel
          - id: 462062816
            name: Microsoft PowerPoint
          - id: 784801555
            name: Microsoft OneNote
          - id: 823766827
            name: OneDrive
          - id: 470158793
            name: Keka
          - id: 1490048917
            name: Taskade
          - id: 1291898086
            name: Toggl
          - id: 6469021132
            name: PDFgear
          - id: 411643860
            name: DaisyDisk
          - id: 442168834
            name: SiteSucker

    # Custom DMG installations
    - role: dmg_installer
      tags: [apps, dmg]

    # Dotfiles
    - role: osx_provisioner.collection.homeshick
      tags: [dotfiles]
      vars:
        homeshick_dotfiles_repo: https://github.com/rschlaefli/dotfiles
        homeshick_force: true

    # Programming languages
    - role: osx_provisioner.collection.asdf
      when: configure_asdf | bool
      tags: [dev, languages]
      vars:
        asdf_plugins:
          # - name: "nodejs"
          #   versions: ["18.17.1"]
          #   global: "18.17.1"
          # - name: "python"
          #   versions: ["3.11.4"]
          #   global: "3.11.4"
          - name: "java"
            versions: ["latest"]
            global: "latest"
          # - name: "erlang"
          #   environment: {}
          #   pre_install: ""
          #   repository: ""
          #   versions:
          #     - 23.3.3
          #     - 23.3.4
          #   delete_versions: []
          #   global: 23.3.4

    # Firewall configuration
    - role: osx_provisioner.collection.firewall
      when: configure_firewall | bool
      tags: [security, firewall]
      vars:
        firewall_enabled: true
        firewall_stealth_mode_enabled: true
        firewall_pf_anchors:
        - name: local_domain.pf
          description: Forward port 80 to 8088 for local domains
          rules: |
            rdr pass on lo0 inet proto tcp from any to self port 80 -> 127.0.0.1 port 8088
            rdr pass on en0 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8088
            rdr pass on en1 inet proto tcp from any to any port 80 -> 127.0.0.1 port 8088

    # Dock configuration
    - role: geerlingguy.mac.dock
      when: configure_dock | bool
      tags: [ui, dock]
      vars:
        dockutil_install: false
        dockitems_remove:
          - Launchpad
          - Safari
          - Photos
          - FaceTime
          - Calendar
          - Contacts
          - Reminders
          - Notes
          - Freeform
          - Music
          - Keynote
          - Numbers
          - Pages
          - TV
          - Podcasts
          - App Store
          - System Settings
          - Mail
          - Maps
          - Messages
        dockitems_persist:
          - name: Zen
            path: /Applications/Zen.app/
            pos: 1
          - name: Warp
            path: /Applications/Warp.app/
            pos: 2
          - name: Cursor
            path: /Applications/Cursor.app/
            pos: 3
          - name: Claude
            path: /Applications/Claude.app/
            pos: 4
          - name: Craft
            path: /Applications/Craft.app/
            pos: 5
          - name: ClickUp
            path: /Applications/ClickUp.app/
            pos: 6
          - name: Microsoft Teams
            path: /Applications/Microsoft Teams.app/
            pos: 7
          - name: Spotify
            path: /Applications/Spotify.app/
            pos: 8

    # OS settings and preferences
    - role: settings
      when: configure_settings | bool
      tags: [settings]
