- name: Setup ubuntu
  hosts: 127.0.0.1
  roles:
    - bootstrap
    - packages
    - git
    - docker
    - node
    - java
    - scala
    - r
    - vpn
  vars:
    git_user_name: Roland Schlaefli
    git_user_email: rolandschlaefli@gmail.com