# TODO: setup startup applications

- name: Ensure that a ~/bin directory is available
  become: yes
  become_user: '{{account_name}}'
  file:
    path: '/home/{{account_name}}/bin'
    state: directory

- name: Install the gnome tweaks application
  apt:
    name: gnome-tweak-tool
    state: latest

- name: Install the base for gnome shell extensions
  apt:
    name: chrome-gnome-shell
    state: latest

- name: Install microsoft core fonts
  apt:
    name: ttf-mscorefonts-installer
    state: latest
  environment:
    ACCEPT_EULA: 'y'
  when: "'microsoft-fonts' in install_packages"

- name: Install pomodoro timer
  apt:
    name: gnome-shell-pomodoro
    state: latest
  when: "'pomodoro' in install_packages"

- name: Install caffeine
  apt:
    name: caffeine
    state: latest
  when: "'caffeine' in install_packages"

- name: Install filezilla
  apt:
    name: filezilla
    state: latest
  when: "'filezilla' in install_packages"

- include_tasks: pomodone.yml
  when: "'pomodone' in install_packages"
  
- include_tasks: rescuetime.yml
  when: "'rescuetime' in install_packages"
  
- include_tasks: vscode.yml
  when: "'vscode' in install_packages"
  
- include_tasks: zsh.yml
  when: "'zsh' in install_packages"

# - include_tasks: flatpak.yml

# - name: Install git-standup
#   shell: snap install git-standup --edge
#   when: "'git-standup' in install_packages"

# - name: Install snaps
#   shell: snap install {{item}}
#   with_items: '{{ install_snaps }}'

# - name: Install additional packages
#   apt:
#     name: '{{install_additional}}'
#     state: latest
#   when: install_additional is defined
