# TODO: setup startup applications

- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: "3600"

- name: Upgrade all installed APT packages (in safe mode)
  apt:
    upgrade: safe

- name: Install exFAT dependencies
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - exfat-fuse
      - exfat-utils

- name: Ensure that a ~/bin directory is available
  become: yes
  become_user: "{{account_name}}"
  file:
    path: "/home/{{account_name}}/bin"
    state: directory

- name: Install the gnome tweaks application
  apt:
    name: gnome-tweak-tool
    state: latest

- name: Install the base for gnome shell extensions
  apt:
    name: chrome-gnome-shell
    state: latest

- name: Install libsecret
  apt:
    name: libsecret-1-dev
    state: latest

- name: Install microsoft core fonts
  apt:
    name: ttf-mscorefonts-installer
    state: latest
  environment:
    ACCEPT_EULA: "y"

- name: Add ppa repositories
  apt_repository:
    repo: "{{item}}"
    state: present
  loop: "{{packages_ppa}}"

- name: Install apt packages
  apt:
    name: "{{item}}"
    state: latest
  loop: "{{packages_apt}}"

- name: Install deb packages
  apt:
    deb: "{{item}}"
    state: present
  loop: "{{packages_deb}}"
  ignore_errors: yes

- name: Install snap packages (confined)
  snap:
    name: "{{item}}"
    state: present
  loop: "{{packages_snap_confined}}"

- name: Install snap packages (classic)
  snap:
    name: "{{item}}"
    state: present
    classic: yes
  loop: "{{packages_snap_classic}}"

- name: Add startup applications
  become: yes
  template:
    src: startup.desktop
    dest: "/home/{{account_name}}/.config/autostart/"
  loop: "{{packages_startup}}"
