- name: Update APT package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all installed APT packages (in safe mode)
  apt:
    upgrade: safe

- name: Install basic system management packages
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - nano
      - htop
      - gufw

- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- include_tasks: vscode.yml
- include_tasks: flux.yml
- include_tasks: neovim.yml
- include_tasks: drive.yml
# - include_tasks: merge.yml
