- name: Install synology drive
  apt:
      deb: https://global.download.synology.com/download/Tools/SynologyDriveClient/1.1.3-10570/Ubuntu/Installer/x86_64/synology-drive-10570.x86_64.deb
      state: present

- name: Install synology cloud station backup
  apt:
      deb: https://global.download.synology.com/download/Tools/CloudStationBackup/4.2.8-4421/Ubuntu/Installer/x86_64/synology-cloud-station-backup-4421.x86_64.deb
      state: present
