- name: Install zsh
  apt:
    name: zsh
    state: latest

- name: Install antigen
  become: yes
  become_user: "{{account_name}}"
  get_url:
    url: https://git.io/antigen
    dest: ~/.antigen.zsh
    mode: 0700

- name: Download powerline font
  become: yes
  become_user: "{{account_name}}"
  get_url:
    url: https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
    dest: "/home/{{account_name}}/.local/share/fonts/PowerlineSymbols.otf"
    mode: 0700

- name: Update the font cache
  become: yes
  become_user: "{{account_name}}"
  command: "fc-cache -vf /home/{{account_name}}//.local/share/fonts/"

- name: Ensure the fontconfig directory exists
  become: yes
  become_user: "{{account_name}}"
  file:
    path: "/home/{{account_name}}/.config/fontconfig/conf.d"
    state: directory

- name: Install the fontconfig file
  become: yes
  become_user: "{{account_name}}"
  get_url:
    url: https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
    dest: "/home/{{account_name}}/.config/fontconfig/conf.d/10-powerline-symbols.conf"
    mode: 0700

- name: Install .zshrc
  become: yes
  become_user: "{{account_name}}"
  get_url:
    url: https://github.com/rschlaefli/homelab/blob/master/dotfiles/.zshrc
    dest: "/home/{{account_name}}/.zshrc"
    mode: 0700
