# TODO: make sure this installation is idempotent
# TODO: parametrize toolbox version (latest_)

- name: Install JetBrains Toolbox
  become: yes
  become_user: "{{account_name}}"
  unarchive:
        src: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-{{toolbox_version}}.tar.gz"
        dest: "/home/{{account_name}}/bin/station/"
  vars:
        toolbox_version: 1.13.4801
