# TODO: make sure this installation is idempotent
# TODO: parametrize toolbox version (latest_)

- name: Install JetBrains Toolbox
  become: yes
  become_user: roland
  unarchive:
    src: "https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.13.4801.tar.gz"
    dest: "/home/bin"
  
