# https://www.scala-sbt.org/1.0/docs/Installing-sbt-on-Linux.html

- name: Add the sbt repository key
  apt_key:
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      keyserver: keyserver.ubuntu.com
      state: present

- name: Add the sbt repository
  apt_repository:
      repo: deb https://dl.bintray.com/sbt/debian /
      state: present

- name: Install sbt
  apt:
      name: sbt
      state: latest
