# install neovim

- name: Add the neovim repository for 18.04
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: present
  when: ansible_distribution_release == 'bionic'

- name: Ensure the neovim ppa is not used in 18.10
  apt_repository:
    repo: ppa:neovim-ppa/stable
    state: absent
  when: ansible_distribution_release == 'cosmic'

- name: Install neovim
  apt:
    name: neovim
    state: latest
