# TODO: parametrize java versions

- name: Install maven
  apt:
      name: maven
      state: latest

- name: Install JDK 8
  apt:
      name: openjdk-8-jdk
      state: latest
  when: ansible_distribution_release != 'disco'

- name: Install JDK 11
  apt:
      name: openjdk-11-jdk
      state: latest

- name: Make JDK 8 the default executor
  alternatives:
      name: java
      path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: ansible_distribution_release != 'disco'
