- name: Install the undervolt package
  pip:
    name: undervolt
    state: latest
    executable: pip3

- name: Create a service for undervolting on startup
  template:
    src: undervolt.service
    dest: /etc/systemd/system/undervolt.service

- name: Create a service for undervolting on resume
  template:
    src: undervolt-resume.service
    dest: /etc/systemd/system/undervolt-resume.service

- name: Install a timer for the undervolt service
  template:
    src: undervolt.timer
    dest: /etc/systemd/system/undervolt.timer

- name: Start the timer for the undervolt service
  systemd:
    state: started
    name: undervolt.timer
    daemon_reload: yes
