# install f.lux for night mode
# manually set location to -77.9527, 166.4895 for always-on

# DEPRECATED: use night light

- name: Add the flux repository
  apt_repository:
        repo: ppa:nathan-renniewaldock/flux
        state: present

- name: Install fluxgui
  apt:
        name: fluxgui
        state: latest
